[FSTORE-549] Uploading a large number of rows to onlinefs fails with TOPIC_AUTHORIZATION_FAILED
logicalclocks/hops-kafka-authorizer pull request #16
Opened 2023-01-11 15:05 UTC by bubriks

2023-01-11 21:40 UTC, SirOibaf commented on src/test/java/io/hops/kafka/TestHopsPrincipalBuilder.java
> +    Principal originPrincipal = new X500Principal("CN=my_common_name,OU=0,C=SE,O=organization");
The order here was intentional leave it as it was please

2023-01-11 21:41 UTC, SirOibaf commented on src/test/java/io/hops/kafka/TestHopsPrincipalBuilder.java
> -    Assert.assertEquals("another_common_name", p.getName());
Same here, leave the test as it was

2023-01-12 16:26 UTC, moritzmeister commented on src/main/java/io/hops/kafka/HopsAclAuthorizer.java
> +            LOG.info("Invalidating cache for"
Doesn't this generate a lot of log messages?

2023-01-12 16:26 UTC, moritzmeister commented on src/main/java/io/hops/kafka/HopsAclAuthorizer.java
> +        .filter(hopsAcl -> hopsAcl.getPrincipal().equals(projectName__userName)).collect(Collectors.toList());
Wondering if we should keep the inner Map structure keyed by principal, so that we don't have to iterate over all acls for every request.

2023-01-12 16:26 UTC, moritzmeister commented on src/main/java/io/hops/kafka/DbConnection.java
> +    List<HopsAcl> aclList = new ArrayList<>();
Maybe we should keep the inner Map to avoid iterating over the list for every request.

2023-01-13 08:22 UTC, bubriks commented on src/main/java/io/hops/kafka/HopsAclAuthorizer.java
> +            LOG.info("Invalidating cache for"
Currently, there is a huge amounts of log messages being generated, after these changes it is actually slightly less. I think we maybe should reconconcider what should be logged, or at least logging levels. (I can removed this log if you wish)

2023-01-13 12:45 UTC, moritzmeister commented on src/main/java/io/hops/kafka/HopsAclAuthorizer.java
> +            LOG.info("Invalidating cache for"
The authorizer is on level wARN by default so it's fine I think

2023-01-13 14:03 UTC, moritzmeister commented on src/main/java/io/hops/kafka/DbConnection.java
> +        topicAcls = new HashMap<>();
this is not necessary since it's initialized with an empty map already.

2023-01-13 15:10 UTC, moritzmeister approved these changes

2023-01-16 08:58 UTC, SirOibaf requested changes

2023-01-16 08:58 UTC, SirOibaf commented on pom.xml
> +    <guava.version>30.1-jre</guava.version>
Kafka already brings Guava dependency (version 20.0) - I think it would be wise to have the same version, otherwise we risk ending up with classpath and method not found exceptions.

2023-01-16 08:58 UTC, SirOibaf commented on src/main/java/io/hops/kafka/DbConnection.java
> +        String command = String.format(SQL_COMMAND_SPECIFIC, topicName);
This is standard SQL Injection :) Use PreparedStatement here!

2023-01-16 08:58 UTC, SirOibaf commented on src/main/java/io/hops/kafka/HopsAclAuthorizer.java
> +  private LoadingCache<String, Map<String, List<HopsAcl>>> aclMapping;
I would keep this comment here: 
```
//<TopicName,<Principal,HopsAcl>>
```
So that we know what the 2 Strings are for

2023-01-16 12:06 UTC, SirOibaf approved these changes

2023-01-16 12:28 UTC, merged