[FSTORE-588] Kafka Authoriser Update
logicalclocks/hops-kafka-authorizer pull request #19
Opened 2023-01-31 13:22 UTC by bubriks

2023-02-08 13:42 UTC, moritzmeister commented on src/main/java/io/hops/kafka/DbConnection.java
> +  private static final String SQL_SELECT_SHARED_PROJECT = "SELECT dsw.permission " +
If everything is shared in read-only, do we actually need this?

2023-02-08 13:42 UTC, moritzmeister commented on src/main/java/io/hops/kafka/HopsAclAuthorizer.java
> +  private LoadingCache<String, Integer> topicProject;
Can you add comments on what these mappings are, e.g. topicName -> project id of topic

2023-02-08 13:42 UTC, moritzmeister commented on src/main/java/io/hops/kafka/HopsAclAuthorizer.java
> +  private LoadingCache<Pair<Integer, Integer>, String> projectShare;
I wonder if this is needed for all users, since we only allow sharing in the same mode for all users?

2023-02-08 13:42 UTC, moritzmeister commented on src/main/java/io/hops/kafka/HopsAclAuthorizer.java
> +            return dbConnection.getTopicProject(topicName);
Do we need to catch the SQL exception and log it?

2023-02-08 13:42 UTC, moritzmeister commented on src/main/java/io/hops/kafka/HopsAclAuthorizer.java
> +        int topicProjectId = topicProject.get(topicName);
We don't have the project id somewhere in the request?

2023-02-08 13:42 UTC, moritzmeister commented on src/main/java/io/hops/kafka/HopsAclAuthorizer.java
> +        int topicProjectId = topicProject.get(topicName);
Can't you get the projectId from the same query where you lookup the user role? Since you lookup anyway on project name? That one should be the right Id, or not?

2023-02-08 13:42 UTC, moritzmeister commented on src/main/java/io/hops/kafka/HopsAclAuthorizer.java
> +      } catch (ExecutionException e) {
This one is raised by the loading cache, do we want to cache the SQL exception here too?

2023-02-08 13:42 UTC, moritzmeister commented on src/main/java/io/hops/kafka/HopsAclAuthorizer.java
> +        if (topicProjectId == userProjectId) {
When a user tries to write to a topic, is he going to do that from the shared project or from his origin/shared with project?

2023-02-08 13:48 UTC, bubriks commented on src/main/java/io/hops/kafka/DbConnection.java
> +  private static final String SQL_SELECT_SHARED_PROJECT = "SELECT dsw.permission " +
Right now we just have to make sure that it is shared, I could also return something different (like bool) to identify that it is shared, but I thought this would be simpler.

2023-02-08 13:57 UTC, bubriks commented on src/main/java/io/hops/kafka/HopsAclAuthorizer.java
> +            return dbConnection.getTopicProject(topicName);
it is caught as `ExecutionException` and logged in a single place. https://github.com/bubriks/hops-kafka-authorizer/blob/FSTORE-588/src/main/java/io/hops/kafka/HopsAclAuthorizer.java#L190

2023-02-08 14:00 UTC, bubriks commented on src/main/java/io/hops/kafka/HopsAclAuthorizer.java
> +      } catch (ExecutionException e) {
this `ExecutionException` encompasses the `SQLException` (you can get it by calling `e.getCause()`). If there is `SQLException`  it is logged here.

2023-02-08 14:05 UTC, bubriks commented on src/main/java/io/hops/kafka/HopsAclAuthorizer.java
> +        int topicProjectId = topicProject.get(topicName);
As far as I know we have only the project name (as part of the principle). I cant get the project that is being used any other way.
the project id that I get when looking up the user role is the project that the user uses currently, but if the user is working on a shared project, then it will not be the same as the topic's project id (since the user in the project 119 could be working on a topic in project 120).

2023-02-08 14:08 UTC, bubriks commented on src/main/java/io/hops/kafka/HopsAclAuthorizer.java
> +  private LoadingCache<Pair<Integer, Integer>, String> projectShare;
yes i could make it a set, and check if key is there, but I thought since I am returning share permission I could save them (Since it doesn't take up a lot of space either way and they are relatively quickly invalidated, furthermore, if we decide to later allow sharing with different permission it would be a straight forward change here).

2023-02-09 09:57 UTC, bubriks commented on src/main/java/io/hops/kafka/HopsAclAuthorizer.java
> +      } catch (ExecutionException e) {
in log it looks like this:
`2023-02-09 08:21:01,886 ERROR kafka.authorizer.logger: Failed to authorize user 'cccc__meb10000' to perform 'Describe' on topic '1145_1081_test_kafka_1_onlinefs', retries left: 1
java.util.concurrent.ExecutionException: java.sql.SQLException: Illegal operation on empty result set.
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:500)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:459)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:76)
	at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:142)
	at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2373)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2337)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2295)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2208)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4053)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4057)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4986)
	at io.hops.kafka.HopsAclAuthorizer.authorizeProjectUser(HopsAclAuthorizer.java:188)
	at io.hops.kafka.HopsAclAuthorizer.authorize(HopsAclAuthorizer.java:168)
	at kafka.server.KafkaApis$$anonfun$kafka$server$KafkaApis$$authorize$1.apply(KafkaApis.scala:424)
	at kafka.server.KafkaApis$$anonfun$kafka$server$KafkaApis$$authorize$1.apply(KafkaApis.scala:424)
	at scala.Option.forall(Option.scala:247)
	at kafka.server.KafkaApis.kafka$server$KafkaApis$$authorize(KafkaApis.scala:424)
	at kafka.server.KafkaApis$$anonfun$19.apply(KafkaApis.scala:1033)
	at kafka.server.KafkaApis$$anonfun$19.apply(KafkaApis.scala:1033)
	at scala.collection.TraversableLike$$anonfun$partition$1.apply(TraversableLike.scala:314)
	at scala.collection.TraversableLike$$anonfun$partition$1.apply(TraversableLike.scala:314)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:94)
	at scala.collection.TraversableLike$class.partition(TraversableLike.scala:314)
	at scala.collection.AbstractTraversable.partition(Traversable.scala:104)
	at kafka.server.KafkaApis.handleTopicMetadataRequest(KafkaApis.scala:1033)
	at kafka.server.KafkaApis.handle(KafkaApis.scala:116)
	at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:69)
	at java.lang.Thread.run(Thread.java:750)`

2023-02-21 09:38 UTC, moritzmeister commented on src/main/java/io/hops/kafka/HopsAclAuthorizer.java
> +  private LoadingCache<Pair<Integer, Integer>, String> projectShare;
sounds good.

2023-02-21 10:15 UTC, moritzmeister commented on src/main/java/io/hops/kafka/HopsAclAuthorizer.java
> +            return dbConnection.getTopicProject(topicName);
Where is the SQL exception coming from then?

2023-02-21 10:16 UTC, moritzmeister commented on src/main/java/io/hops/kafka/HopsAclAuthorizer.java
> +        int topicProjectId = topicProject.get(topicName);
okay got it

2023-02-21 10:22 UTC, moritzmeister commented on src/main/java/io/hops/kafka/HopsAclAuthorizer.java
> +      } catch (ExecutionException e) {
Ah I see, the loading cache wraps it.

2023-02-21 10:23 UTC, moritzmeister commented on src/main/java/io/hops/kafka/HopsAclAuthorizer.java
> +            return dbConnection.getTopicProject(topicName);
nvm, I saw your other comment, since we don't call load explicitly, we will always only get ExecutionException

2023-02-21 10:23 UTC, bubriks commented on src/main/java/io/hops/kafka/HopsAclAuthorizer.java
> +            return dbConnection.getTopicProject(topicName);
The SQLException potentialy comes from getTopicProject (any issue with SQL execution). But when calling LoggingCache.get method it is returned as ExecutionExcepion (eny exception would be returned like this).

2023-02-21 10:23 UTC, moritzmeister approved these changes

2023-02-21 14:06 UTC, javierdlrm approved these changes
Approved with a minor comment

2023-02-22 08:19 UTC, bubriks commented on src/main/java/io/hops/kafka/Consts.java
> +  public static final String DATA_SCIENTIST = "Data scientist";
No, not really since they are on different projects. It would have been possible if saved in the database and referenced instead.

2023-02-27 09:50 UTC, moritzmeister commented on src/main/java/io/hops/kafka/HopsAclAuthorizer.java
> +    }
Doesn't this mean we can never return `true` for the offsets topic?

I was expecting something like this, but maybe I am missing somethign
```
if ("__consumer_offsets".equals(topicName)) {
  LOG.debug("topic = " + topicName + " access allowed: " + consumerOffsetsEnabled);
  return consumerOffsetsEnabled
}
```

2023-02-27 10:07 UTC, moritzmeister approved these changes

2023-02-27 23:10 UTC, SirOibaf requested changes

2023-02-27 23:10 UTC, SirOibaf commented on src/main/java/io/hops/kafka/DbConnection.java
> +      resultSet.next();
How do you know that there is a single line in the database? The `project_topics` doesn't have a unique constraint on the `topic_name`. 
I'm quite sure that Kafka does not let you create 2 topics with the same name, but consider the Hopsworks schema, I'm concerned on how this is handled in Hopsworks. I would not be surprised if 2 rows are created in the database and this query breaks here.

2023-02-28 08:23 UTC, bubriks commented on src/main/java/io/hops/kafka/DbConnection.java
> +      resultSet.next();
I can add a limit of 1 but even if right now if there would be 2 or more topics with the same name this method would just use the 1st and ignoring the rest. Also if you want we can add a unique constraint to the topic name field.

2023-02-28 14:44 UTC, bubriks commented on src/main/java/io/hops/kafka/DbConnection.java
> +      resultSet.next();
If we add a unique constraint to a column that is not unique we get an SQL exception and no change is enacted. If we want to ensure that everything is ok, we would need to manually remove duplicates.

2023-03-01 09:11 UTC, bubriks commented on src/main/java/io/hops/kafka/DbConnection.java
> +      resultSet.next();
I ran a quick test and here are the results. I created 2 topics with the same name
`
mysql> select * from project_topics;
+----------------+------------+----+------------+----------------+--------------+
| topic_name     | project_id | id | subject_id | num_partitions | num_replicas |
+----------------+------------+----+------------+----------------+--------------+
| 119_13_ui_fg_1 |        119 |  1 |          5 |             10 |            1 |
| 119_13_ui_fg_1 |        120 |  2 |          5 |             10 |            1 |
+----------------+------------+----+------------+----------------+--------------+
`
when getting by topic name the current solution tends to use only: `ProjectID '119' topic '119_13_ui_fg_1'`

2023-03-01 09:46 UTC, moritzmeister commented on src/main/java/io/hops/kafka/DbConnection.java
> +      resultSet.next();
That means, based on name we have no way to know which project a topic belongs to?

2023-03-01 09:48 UTC, SirOibaf commented on src/main/java/io/hops/kafka/DbConnection.java
> +      resultSet.next();
I don't understand how this even works in Kafka to be honest.

2023-03-01 21:42 UTC, SirOibaf approved these changes

2023-03-02 09:25 UTC, merged